### ISSUE TITLE
delta_1  | Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/nodemon/bin/postinstall'

### ISSUE THREAD

**Issue by ralyodio** [fosslife/delta#16]
delta_1  | Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/nodemon/bin/postinstall'

**Comment by Sparkenstein** [comment]
Can you tell me a bit more about this error?
When does the error occurs? `nodemon` is a dev dependency, unless you are planning to contribute 
to the codebase itself, you can skip the dev dependencies installation. 
try `npm install --only=prod`
regardless of that, I didn't face this issue when I cloned a new instance of `delta`, you may wanna provide additional information about how to reproduce this issue
